import ExcelJS from "exceljs";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth";
import { apiError } from "@/lib/api-response";
import { csrfError } from "@/lib/request-security";
import { readableNik } from "@/lib/nik-crypto";
import { writeAudit } from "@/lib/audit";

export async function POST(request:Request){try{const rejected=csrfError(request);if(rejected)return rejected;const admin=await requireAdmin();const body=await request.json().catch(()=>({}));const status=typeof body.status==="string"&&body.status?body.status:undefined;const residents=await prisma.resident.findMany({where:status?{status}:undefined,include:{createdBy:{select:{name:true}}},orderBy:{createdAt:"desc"}});const workbook=new ExcelJS.Workbook();workbook.creator="SIPEDAW";const sheet=workbook.addWorksheet("Data Warga");sheet.columns=[{header:"NIK",key:"nik",width:20},{header:"Nama",key:"name",width:28},{header:"Jenis Kelamin",key:"gender",width:18},{header:"Tanggal Lahir",key:"birthDate",width:16},{header:"Alamat",key:"address",width:40},{header:"RT",key:"rt",width:8},{header:"RW",key:"rw",width:8},{header:"Desa/Kelurahan",key:"village",width:22},{header:"Kecamatan",key:"district",width:22},{header:"Nomor HP",key:"phone",width:18},{header:"Status",key:"status",width:20},{header:"Petugas",key:"officer",width:24},{header:"Dibuat",key:"createdAt",width:22}];for(const r of residents)sheet.addRow({nik:readableNik(r),name:r.fullName,gender:r.gender==="MALE"?"Laki-laki":"Perempuan",birthDate:r.birthDate,address:r.address,rt:r.rt,rw:r.rw,village:r.village,district:r.district,phone:r.phoneNumber,status:r.status,officer:r.createdBy.name,createdAt:r.createdAt});sheet.getRow(1).font={bold:true};sheet.views=[{state:"frozen",ySplit:1}];sheet.autoFilter={from:"A1",to:"M1"};const log=await prisma.exportLog.create({data:{actorId:admin.id,recordCount:residents.length,filters:status?{status}:undefined}});await writeAudit({actorId:admin.id,action:"RESIDENTS_EXPORTED",entityType:"ExportLog",entityId:log.id,metadata:{recordCount:residents.length,status}});const buffer=await workbook.xlsx.writeBuffer();const stamp=new Date().toISOString().slice(0,10);return new Response(Buffer.from(buffer),{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="data-warga-${stamp}.xlsx"`,"Cache-Control":"no-store"}});}catch{return apiError("Export XLSX gagal. Periksa konfigurasi enkripsi NIK.",500,"EXPORT_FAILED");}}
