"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

type User = { id:string; name:string; username:string; role:string; teamId:string|null; isActive:boolean; team:{name:string}|null };
type Team = { id:string; name:string; isActive:boolean };
const blank = { name:"", username:"", password:"", role:"FIELD_OFFICER", teamId:"", isActive:true };

export function UserManager({ currentUserId }:{ currentUserId:string }) {
  const [users,setUsers]=useState<User[]>([]); const [teams,setTeams]=useState<Team[]>([]);
  const [editing,setEditing]=useState<string|null>(null); const [form,setForm]=useState(blank); const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const[a,b]=await Promise.all([fetch("/api/admin/users"),fetch("/api/admin/teams")]);const[ua,tb]=await Promise.all([a.json(),b.json()]);if(a.ok)setUsers(ua.data);if(b.ok)setTeams(tb.data);},[]);
  useEffect(()=>{void load()},[load]);
  async function save(e:FormEvent){e.preventDefault();const isNew=editing==="new";const payload={...form,teamId:form.teamId||null,...(!isNew&&!form.password?{password:undefined}:{})};if(isNew)delete (payload as Partial<typeof payload>).isActive;const r=await fetch(isNew?"/api/admin/users":`/api/admin/users/${editing}`,{method:isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setMessage(j.message);if(r.ok){setEditing(null);setForm(blank);await load()}}
  async function disable(id:string){if(!confirm("Nonaktifkan user ini?"))return;const r=await fetch(`/api/admin/users/${id}`,{method:"DELETE"});const j=await r.json();setMessage(j.message);if(r.ok)await load()}
  function edit(u:User){setEditing(u.id);setForm({name:u.name,username:u.username,password:"",role:u.role,teamId:u.teamId||"",isActive:u.isActive})}
  return <div className="grid"><div className="card"><button onClick={()=>{setEditing("new");setForm(blank)}}>Tambah user</button>{message&&<p className="alert">{message}</p>}<div className="table-wrap"><table><thead><tr><th>Nama</th><th>Username</th><th>Role</th><th>Tim</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.username}</td><td>{u.role}</td><td>{u.team?.name||"-"}</td><td>{u.isActive?"Aktif":"Nonaktif"}</td><td className="actions"><button className="secondary" onClick={()=>edit(u)}>Edit</button>{u.id!==currentUserId&&u.isActive&&<button className="danger-button" onClick={()=>disable(u.id)}>Nonaktifkan</button>}</td></tr>)}</tbody></table></div></div>{editing&&<form className="card form-grid" onSubmit={save}><h2 className="full">{editing==="new"?"Tambah user":"Edit user"}</h2><label>Nama<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Username<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password {editing!=="new"&&"(kosongkan jika tetap)"}<input type="password" required={editing==="new"} minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="FIELD_OFFICER">Petugas</option><option value="ADMIN">Admin</option></select></label><label>Tim<select value={form.teamId} disabled={form.role==="ADMIN"} onChange={e=>setForm({...form,teamId:e.target.value})}><option value="">Tanpa tim</option>{teams.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{editing!=="new"&&<label><span>Status aktif</span><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/></label>}<div className="full actions"><button>Simpan</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Batal</button></div></form>}</div>;
}
