import { prisma } from "@/lib/prisma";
import { requireSession } from "@/lib/auth";
import { apiError, apiSuccess } from "@/lib/api-response";
import { csrfError } from "@/lib/request-security";
import { correctionSchema } from "@/validation/resident";
import { writeAudit } from "@/lib/audit";

export async function GET(){try{const user=await requireSession();if(user.role!=="FIELD_OFFICER")return apiError("Akses ditolak.",403,"FORBIDDEN");const items=await prisma.correctionRequest.findMany({where:{requestedById:user.id},include:{resident:{select:{fullName:true,nikLastFour:true}},reviewedBy:{select:{name:true}}},orderBy:{createdAt:"desc"}});return apiSuccess(items);}catch{return apiError("Akses ditolak.",403,"FORBIDDEN");}}

export async function POST(request:Request){try{const rejected=csrfError(request);if(rejected)return rejected;const user=await requireSession();if(user.role!=="FIELD_OFFICER")return apiError("Akses ditolak.",403,"FORBIDDEN");const parsed=correctionSchema.safeParse(await request.json());if(!parsed.success)return apiError("Pengajuan belum valid.",400,"VALIDATION_ERROR",parsed.error.flatten());const resident=await prisma.resident.findFirst({where:{id:parsed.data.residentId,createdById:user.id,status:{not:"INACTIVE"}},select:{id:true}});if(!resident)return apiError("Data warga tidak ditemukan atau bukan input Anda.",404,"NOT_FOUND");const pending=await prisma.correctionRequest.findFirst({where:{residentId:resident.id,status:"PENDING"}});if(pending)return apiError("Masih ada pengajuan yang menunggu review.",409,"PENDING_EXISTS");const correction=await prisma.$transaction(async tx=>{const created=await tx.correctionRequest.create({data:{residentId:resident.id,requestedById:user.id,reason:parsed.data.reason,proposedData:parsed.data.proposedData}});await tx.resident.update({where:{id:resident.id},data:{status:"NEEDS_CORRECTION"}});return created;});await writeAudit({actorId:user.id,action:"CORRECTION_REQUESTED",entityType:"CorrectionRequest",entityId:correction.id,metadata:{residentId:resident.id}});return apiSuccess({id:correction.id},"Pengajuan koreksi dikirim.",201);}catch{return apiError("Pengajuan koreksi gagal disimpan.",500,"INTERNAL_ERROR");}}
