"use client";
import { DataTable } from "@/components/data-table";

import { FormEvent, useCallback, useState } from "react";

type Row={id:string;nikLastFour:string;fullName:string;rt:string;rw:string;status:string;createdBy:{name:string}};
const empty={nik:"",fullName:"",gender:"",birthDate:"",address:"",rt:"",rw:"",village:"",district:"",phoneNumber:"",note:"",status:"UNVERIFIED"};
export function ResidentManager(){const [revision,setRevision]=useState(0);const [status,setStatus]=useState("");const [editing,setEditing]=useState<string|null>(null);const [form,setForm]=useState<Record<string,string>>(empty);const [message,setMessage]=useState("");
const load=useCallback(async()=>{setRevision(value=>value+1);},[]);
async function edit(id:string){setMessage("");const r=await fetch(`/api/admin/residents/${id}`);const j=await r.json();if(!r.ok)return setMessage(j.message);const d=j.data;setEditing(id);setForm({...empty,...d,address:d.address??"",village:d.village??"",district:d.district??"",phoneNumber:d.phoneNumber??"",note:d.note??"",birthDate:d.birthDate?String(d.birthDate).slice(0,10):"",nik:d.nik});}
async function save(e:FormEvent){e.preventDefault();const isNew=editing==="new";const payload=isNew?Object.fromEntries(Object.entries(form).filter(([key])=>key!=="status")):form;const r=await fetch(isNew?"/api/residents":`/api/admin/residents/${editing}`,{method:isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setMessage(j.message);if(r.ok){setEditing(null);setForm(empty);await load();}}
async function deactivate(id:string){if(!confirm("Nonaktifkan warga ini tanpa menghapus datanya?"))return;const r=await fetch(`/api/admin/residents/${id}`,{method:"DELETE"});const j=await r.json();setMessage(j.message);if(r.ok)await load();}
return <div className="grid"><div className="card"><div className="toolbar"><select aria-label="Filter status warga" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option><option value="UNVERIFIED">Belum diverifikasi</option><option value="VERIFIED">Terverifikasi</option><option value="NEEDS_CORRECTION">Perlu koreksi</option><option value="INACTIVE">Nonaktif</option></select><button onClick={()=>{setEditing("new");setForm(empty)}}>Tambah warga</button></div>{message&&<div className="alert">{message}</div>}<DataTable<Row> endpoint={`/api/admin/residents?status=${status}`} revision={revision} searchPlaceholder="Cari nama, NIK (4 digit), RT/RW, petugas" columns={[
 {key:"nikLastFour",label:"NIK",value:r=>r.nikLastFour,render:r=>"************"+r.nikLastFour},
 {key:"fullName",label:"Nama",value:r=>r.fullName},
 {key:"rt",label:"RT/RW",value:r=>r.rt+"/"+r.rw},
 {key:"status",label:"Status",value:r=>r.status,render:r=><span className="badge">{r.status}</span>},
 {key:"createdBy",label:"Petugas",value:r=>r.createdBy.name},
 {key:"actions",label:"Aksi",className:"actions",render:r=><><button className="secondary" onClick={()=>edit(r.id)}>Edit</button>{r.status!=="INACTIVE"&&<button className="danger-button" onClick={()=>deactivate(r.id)}>Nonaktifkan</button>}</>}
 ]}/></div>{editing&&<div className="card"><h2>{editing==="new"?"Tambah warga":"Edit dan verifikasi warga"}</h2><form className="form-grid" onSubmit={save}>{Object.entries({nik:"NIK",fullName:"Nama lengkap",birthDate:"Tanggal lahir",address:"Alamat",rt:"RT",rw:"RW",village:"Desa/Kelurahan",district:"Kecamatan",phoneNumber:"Nomor HP",note:"Catatan"}).map(([key,label])=><label className={["address","note"].includes(key)?"full":""} key={key}>{label}{key==="address"?<textarea value={form[key]} required onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input type={key==="birthDate"?"date":"text"} value={form[key]} required={["nik","fullName","rt","rw"].includes(key)} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<label>Jenis kelamin<select value={form.gender} required onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Pilih</option><option value="MALE">Laki-laki</option><option value="FEMALE">Perempuan</option></select></label>{editing!=="new"&&<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="UNVERIFIED">Belum diverifikasi</option><option value="VERIFIED">Terverifikasi</option><option value="NEEDS_CORRECTION">Perlu koreksi</option><option value="INACTIVE">Nonaktif</option></select></label>}<div className="full actions"><button>Simpan</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Batal</button></div></form></div>}</div>}
