"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Row={id:string;nikLastFour:string;fullName:string;rt:string;rw:string;status:string;createdBy:{name:string}};
const empty={nik:"",fullName:"",gender:"",birthDate:"",address:"",rt:"",rw:"",village:"",district:"",phoneNumber:"",note:"",status:"UNVERIFIED"};
export function ResidentManager(){const [rows,setRows]=useState<Row[]>([]);const [search,setSearch]=useState("");const [status,setStatus]=useState("");const [editing,setEditing]=useState<string|null>(null);const [form,setForm]=useState<Record<string,string>>(empty);const [message,setMessage]=useState("");
const load=useCallback(async()=>{const r=await fetch(`/api/admin/residents?search=${encodeURIComponent(search)}&status=${status}`);const j=await r.json();if(r.ok)setRows(j.data.items);},[search,status]);useEffect(()=>{void load();},[load]);
async function edit(id:string){setMessage("");const r=await fetch(`/api/admin/residents/${id}`);const j=await r.json();if(!r.ok)return setMessage(j.message);const d=j.data;setEditing(id);setForm({...empty,...d,address:d.address??"",village:d.village??"",district:d.district??"",phoneNumber:d.phoneNumber??"",note:d.note??"",birthDate:d.birthDate?String(d.birthDate).slice(0,10):"",nik:d.nik});}
async function save(e:FormEvent){e.preventDefault();const isNew=editing==="new";const payload=isNew?Object.fromEntries(Object.entries(form).filter(([key])=>key!=="status")):form;const r=await fetch(isNew?"/api/residents":`/api/admin/residents/${editing}`,{method:isNew?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setMessage(j.message);if(r.ok){setEditing(null);setForm(empty);await load();}}
async function deactivate(id:string){if(!confirm("Nonaktifkan warga ini tanpa menghapus datanya?"))return;const r=await fetch(`/api/admin/residents/${id}`,{method:"DELETE"});const j=await r.json();setMessage(j.message);if(r.ok)await load();}
return <div className="grid"><div className="card"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option><option value="UNVERIFIED">Belum diverifikasi</option><option value="VERIFIED">Terverifikasi</option><option value="NEEDS_CORRECTION">Perlu koreksi</option><option value="INACTIVE">Nonaktif</option></select><button onClick={()=>{setEditing("new");setForm(empty)}}>Tambah warga</button></div>{message&&<div className="alert">{message}</div>}<div className="table-wrap"><table><thead><tr><th>NIK</th><th>Nama</th><th>RT/RW</th><th>Status</th><th>Petugas</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>************{r.nikLastFour}</td><td>{r.fullName}</td><td>{r.rt}/{r.rw}</td><td><span className="badge">{r.status}</span></td><td>{r.createdBy.name}</td><td className="actions"><button className="secondary" onClick={()=>edit(r.id)}>Edit</button>{r.status!=="INACTIVE"&&<button className="danger-button" onClick={()=>deactivate(r.id)}>Nonaktifkan</button>}</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="muted">Belum ada data.</td></tr>}</tbody></table></div></div>{editing&&<div className="card"><h2>{editing==="new"?"Tambah warga":"Edit dan verifikasi warga"}</h2><form className="form-grid" onSubmit={save}>{Object.entries({nik:"NIK",fullName:"Nama lengkap",birthDate:"Tanggal lahir",address:"Alamat",rt:"RT",rw:"RW",village:"Desa/Kelurahan",district:"Kecamatan",phoneNumber:"Nomor HP",note:"Catatan"}).map(([key,label])=><label className={["address","note"].includes(key)?"full":""} key={key}>{label}{key==="address"?<textarea value={form[key]} required onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input type={key==="birthDate"?"date":"text"} value={form[key]} required={["nik","fullName","rt","rw"].includes(key)} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<label>Jenis kelamin<select value={form.gender} required onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Pilih</option><option value="MALE">Laki-laki</option><option value="FEMALE">Perempuan</option></select></label>{editing!=="new"&&<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="UNVERIFIED">Belum diverifikasi</option><option value="VERIFIED">Terverifikasi</option><option value="NEEDS_CORRECTION">Perlu koreksi</option><option value="INACTIVE">Nonaktif</option></select></label>}<div className="full actions"><button>Simpan</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Batal</button></div></form></div>}</div>}
