"use client";
import { DataTable } from "@/components/data-table";
import{FormEvent,useCallback,useEffect,useState}from"react";type Team={id:string;name:string;code:string;isActive:boolean;_count:{users:number}};const blank={name:"",code:"",isActive:true};export function TeamManager(){const[rows,setRows]=useState<Team[]>([]);const[editing,setEditing]=useState<string|null>(null);const[form,setForm]=useState(blank);const[message,setMessage]=useState("");const load=useCallback(async()=>{const r=await fetch("/api/admin/teams");const j=await r.json();if(r.ok)setRows(j.data)},[]);useEffect(()=>{void load()},[load]);async function save(e:FormEvent){e.preventDefault();const r=await fetch(editing&&editing!=="new"?`/api/admin/teams/${editing}`:"/api/admin/teams",{method:editing&&editing!=="new"?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing==="new"?{name:form.name,code:form.code}:form)});const j=await r.json();setMessage(j.message);if(r.ok){setEditing(null);setForm(blank);await load()}}async function disable(id:string){if(!confirm("Nonaktifkan tim ini? User tidak akan terhapus."))return;const r=await fetch(`/api/admin/teams/${id}`,{method:"DELETE"});const j=await r.json();setMessage(j.message);if(r.ok)await load()}return <div className="grid"><div className="card"><button onClick={()=>{setEditing("new");setForm(blank)}}>Tambah tim</button>{message&&<p className="alert">{message}</p>}<DataTable rows={rows} columns={[
 {key:"code",label:"Kode",value:t=>t.code},
 {key:"name",label:"Nama",value:t=>t.name},
 {key:"members",label:"Anggota",value:t=>t._count.users},
 {key:"status",label:"Status",value:t=>t.isActive?"Aktif":"Nonaktif"},
 {key:"actions",label:"Aksi",className:"actions",render:t=><><button className="secondary" onClick={()=>{setEditing(t.id);setForm({name:t.name,code:t.code,isActive:t.isActive})}}>Edit</button>{t.isActive&&<button className="danger-button" onClick={()=>disable(t.id)}>Nonaktifkan</button>}</>}
 ]}/></div>{editing&&<form className="card form-grid" onSubmit={save}><label>Nama tim<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Kode (huruf besar/angka)<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label>{editing!=="new"&&<label>Status aktif<input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/></label>}<div className="full actions"><button>Simpan</button><button type="button" className="secondary" onClick={()=>setEditing(null)}>Batal</button></div></form>}</div>}
